apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-output-claim
  namespace: exercises
spec:
  storageClassName: cluster-pv-0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
