apiVersion: v1
kind: ConfigMap
metadata:
  name: course-project-config
  namespace: project
data:
  FRONTEND_PORT: "3000"
  BACKEND_PORT: "3002"
  IMAGE_URL: "https://picsum.photos/1200"
  IMAGE_FILE_PATH: "/src/app/data/image.jpg"
