apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-claim
  namespace: project
spec:
  storageClassName: cluster-pv-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
